config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get "/user_questions", to: "questions#user_questions"
  get "/profile", to: "users#profile"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
 end
  root to: "questions#index"
  resources :users
  resources :questions do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  resources :answers, except: [:show] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, class_name: "User"
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
  has_many :answers
  has_many :question_votes

  def upvote(current_user)
    "" \
      "
    # checking if there is a vote for user
    # if there is a previous vote, check for upvote or downvote
    # if previous vote is upvote - no change
    # if previous vote is downvote - toggle upvote and downvote
    " \
      ""
    user_vote = self.question_votes.where(user: current_user).first()

    if self.upvoted?(current_user)
      # do nothing
      return
    elsif self.downvoted?(current_user)
      user_vote.downvote = false
      user_vote.upvote = true
    else
      user_vote =
        QuestionVote.new(user_id: current_user.id, question_id: self.id)
      user_vote.upvote = true
    end

    user_vote.save()
  end

  def downvote(current_user)
    user_vote = self.question_votes.where(user: current_user).first()

    if self.downvoted?(current_user)
      # do nothing
      return
    elsif self.upvoted?(current_user)
      user_vote.upvote = false
      user_vote.downvote = true
    else
      user_vote =
        QuestionVote.new(user_id: current_user.id, question_id: self.id)
      user_vote.downvote = true
    end

    user_vote.save()
  end

  def upvoted?(current_user)
    user_vote = self.question_votes.where(user: current_user).first()
    return user_vote.upvote? if user_vote
    return false
  end

  def downvoted?(current_user)
    user_vote = self.question_votes.where(user: current_user).first()
    return user_vote.downvote? if user_vote
    return false
  end

  def upvotes
    self.question_votes.where(upvote: true).size
  end

  def downvotes
    self.question_votes.where(downvote: true).size
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :redirect_if_not_valid_question_creator, only: %i[edit update]
  before_action :set_question, only: %i[edit update show upvote downvote]

  def index
    if user_signed_in?
      @question = current_user.questions.build
      @all_feed_items = Question.paginate(page: params[:page], per_page: 10)
    end
  end

  def create
    @question = current_user.questions.build(question_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:success] = "Question posted!"
    else
      if @question.content == ""
        flash[:danger] = "Empty question cannot be posted!"
      else
        flash[:danger] = "Question not posted! Try again"
      end
      @all_feed_items = Question.paginate(page: params[:page], per_page: 10)
    end
    redirect_to root_url
  end

  def update
    if @question.update(question_params)
      flash[:success] = "Question updated!"
    else
      flash[:danger] = "Question not updated! Try again..."
    end
    redirect_to question_path(@question)
  end

  def user_questions
    @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
  end

  def show
    @answer = current_user.answers.build()
    if @question.present?
      @answer.question = @question
      @answers = @question.answers.paginate(page: params[:page], per_page: 10)
    end
  end

  def upvote
    @question.upvote(current_user)
    flash[:notice] = "Upvoted"
    redirect_to question_path(@question)
  end

  def downvote
    @question.downvote(current_user)
    flash[:notice] = "Downvoted"
    redirect_to question_path(@question)
  end

  private

  def question_params
    params.require(:question).permit(:content)
  end

  def set_question
    @question = Question.find(params[:id]) if Question.find_by_id(params[:id])
  end

  def redirect_if_not_valid_question_creator
    question = Question.find(params[:id])
    redirect_to question_path(question) if question.user != current_user
  end

  def fetch_question_total_upvotes_downvotes(id)
    question_votes = QuestionVote.where(question_id: id)
    if question_votes.nil?
      return 0, 0
    else
      upvotes = question_votes.sum(:upvote)
      downvotes = question_votes.sum(:downvote)
      return upvotes, downvotes
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  # TODO: move to model
  def question_votes(question_id)
    return QuestionVote.where(question_id: question_id).sum(:upvote) - (QuestionVote.where(question_id: question_id).sum(:downvote))
  end

  # TODO: move to model
  def answer_votes(answer_id)
    return (AnswerVote.where(answer_id: answer_id).sum(:upvote) - AnswerVote.where(answer_id: answer_id).sum(:downvote))
  end
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <b><%= f.label :question %></b><br/>
  <%= f.text_area :content %><br/>
  <%= f.submit 'Update question' %>
<% end %>

app/views/questions/_question.html.erb
<div id="question">
  <p>Question :
    <%= question.content %></p>
  <p>Asked by:&nbsp; <%= question.user.username %></p>
  <p>Posted
    <%= time_ago_in_words(question.created_at) %>
    ago.</p>
  <%= link_to "View question", question_path(question.id) %>
</div>

app/views/questions/edit.html.erb
<h3>Update question</h3>
<%= render 'questions/form' %>

app/views/questions/index.html.erb
<h3>Home section</h3>
<div id='home-block'>
  <section id='post-block'>
    <section id='post-block-header'>
      <img src='https://media.tenor.com/_m9BeUagaMkAAAAi/writing-hand-joypixels.gif'/> &nbsp;
      <p>Post Your Question</p> &nbsp;
      <img src='https://media.tenor.com/_m9BeUagaMkAAAAi/writing-hand-joypixels.gif'/> &nbsp;
    </section>
    <hr/>
    <section id='post-question-form'>
      <%= render "shared/question_form" %>
    </section>
  </section>
  <section id='feed-block'>
    <div id='feed-block-header'>
      <img src='https://media.tenor.com/GL3oJtbTNVoAAAAj/merieducation-online-learning.gif'/> &nbsp;&nbsp;&nbsp;
      <p>Questions Feed</p>
    </div>
    <div id='questions'>
      <ol>
        <%= render @all_feed_items %>
      </ol>
    </div>
    <%= will_paginate @all_feed_items %>
  </section>
</div>

app/views/questions/show.html.erb
<div id='question-block'>
  <p><b>Question :</b><%= @question.content %></p>
  <p>
    <%= link_to '<i class="fa fa-thumbs-o-up" style="font-size:15px"></i>'.html_safe, upvote_question_path(@question) %>
    <%= link_to '<i class="fa fa-thumbs-o-down" style="font-size:15px"></i>'.html_safe, downvote_question_path(@question) %>
    <p>Upvotes: <%= @question.upvotes %></p>
    <p>Downvotes: <%= @question.downvotes %></p>
  </p>
  <% if @question.user == current_user %>
    <p><%= link_to "Edit question", edit_question_path(@question) %></p>
  <% end %>
</div>

<div id='solutions-block'>
  <section id='post-block'>
    <h4>Post your solution here:</h4>
    <%= form_with(url: answers_path, model: @answer, local: true) do |f| %>
      <%= f.hidden_field :question_id, value: @answer.question_id %>
      <div>
        <%= f.text_area :content, placeholder: "Post your solution..." %>
      </div>
      <%= f.submit "Post" %>
    <% end %>
  </section>
  <section id='feed-block'>
    <h4>Solutions</h4>
    <% @question.answers.each do |answer| %>
      <div id="answer">
        <p>Username :<%= answer.user.username %></p>
        <p>Answer :<%= answer.content %></p>
        <p>
          <% if current_user == answer.user %>
            <%= link_to "Edit answer", edit_answer_path(answer) %>
          <% end %>
        </p>
        <p>Posted
          <%= time_ago_in_words(answer.created_at) %>
          ago.</p>
        <p>
          <%= link_to '<i class="fa fa-thumbs-o-up" style="font-size:15px"></i>'.html_safe, upvote_answer_path(answer) %>
          <%= link_to '<i class="fa fa-thumbs-o-down" style="font-size:15px"></i>'.html_safe, downvote_answer_path(answer) %>
          <p>Upvotes: <%= answer.upvotes %></p>
          <p>Downvotes: <%= answer.downvotes %></p>
        </p>
      </div>
    <% end %>
  </section>
</div>

app/views/questions/user_questions.html.erb
<h3>Your Questions</h3>
<% if @feed_items.any? %>
  <ol>
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% else %>
  <p>No questions posted</p>
<% end %>