config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get "/user_questions", to: "questions#user_questions"
  get "/profile", to: "users#profile"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
 end
  root to: "questions#index"
  resources :users
  resources :questions do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  resources :answers, except: [:show] do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
end

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
>

app/views/layouts/_navbar.html.erb
<nav id='navbar-block'>
  <div id='heading-block'>
    <p>Quora App</p>
  </div>
  <div id='navbar-links-block'>
    <section id='section1'>
      <p><%= link_to "Home", root_path %></p>
      <% if user_signed_in? %>
        <p><%= link_to "My questions", user_questions_path %></p>
        <p><%= link_to "Profile", profile_path %></p>
        <p><%= link_to "Sign out", destroy_user_session_path, method: :delete %></p>
      <% else %>
        <p><%= link_to "Sign up", new_user_registration_path %></p>
        <p><%= link_to "Log in", new_user_session_path %></p>
      <% end %>
    </section>
    <section id='section2'>
      <% if user_signed_in? %>
          <span><i class="fa fa-user" aria-hidden="true" style="font-size:120%"></i></span> &nbsp;
          <span>Signed in as <i><%= current_user.username %></i></span>
      <% end %>
    </section>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoraApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div
          class="alert alert-<%= message_type %>"
          style="color:red;font-style:italic"
        >
          <%= message %>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <hr/>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>